var data = [
	{"iau":"Tau", "l_ozvezdje":"Taurus", "ozvezdje":"Bik"},
	{"iau":"Aqr", "l_ozvezdje":"Aquarius", "ozvezdje":"Vodnar"},
	{"iau":"CVn", "l_ozvezdje":"Canes Venatici", "ozvezdje":"Lovska psa"},
	{"iau":"Sco", "l_ozvezdje":"Scorpius", "ozvezdje":"Škorpijon"},
	{"iau":"Ser", "l_ozvezdje":"Serpens", "ozvezdje":"Kača"},
	{"iau":"Sco", "l_ozvezdje":"Scorpius", "ozvezdje":"Škorpijon"},
	{"iau":"Sco", "l_ozvezdje":"Scorpius", "ozvezdje":"Škorpijon"},
	{"iau":"Sgr", "l_ozvezdje":"Sagittarius", "ozvezdje":"Strelec"},
	{"iau":"Oph", "l_ozvezdje":"Ophiuchus", "ozvezdje":"Kačenosec"},
	{"iau":"Oph", "l_ozvezdje":"Ophiuchus", "ozvezdje":"Kačenosec"},
	{"iau":"Sct", "l_ozvezdje":"Scutum", "ozvezdje":"Ščit"},
	{"iau":"Oph", "l_ozvezdje":"Ophiuchus", "ozvezdje":"Kačenosec"},
	{"iau":"Her", "l_ozvezdje":"Hercules", "ozvezdje":"Herkul"},
	{"iau":"Oph", "l_ozvezdje":"Ophiuchus", "ozvezdje":"Kačenosec"},
	{"iau":"Peg", "l_ozvezdje":"Pegasus", "ozvezdje":"Pegaz"},
	{"iau":"Ser", "l_ozvezdje":"Serpens", "ozvezdje":"Kača"},
	{"iau":"Sgr", "l_ozvezdje":"Sagittarius", "ozvezdje":"Strelec"},
	{"iau":"Sgr", "l_ozvezdje":"Sagittarius", "ozvezdje":"Strelec"},
	{"iau":"Oph", "l_ozvezdje":"Ophiuchus", "ozvezdje":"Kačenosec"},
	{"iau":"Sgr", "l_ozvezdje":"Sagittarius", "ozvezdje":"Strelec"},
	{"iau":"Sgr", "l_ozvezdje":"Sagittarius", "ozvezdje":"Strelec"},
	{"iau":"Sgr", "l_ozvezdje":"Sagittarius", "ozvezdje":"Strelec"},
	{"iau":"Sgr", "l_ozvezdje":"Sagittarius", "ozvezdje":"Strelec"},
	{"iau":"Sgr", "l_ozvezdje":"Sagittarius", "ozvezdje":"Strelec"},
	{"iau":"Sgr", "l_ozvezdje":"Sagittarius", "ozvezdje":"Strelec"},
	{"iau":"Sct", "l_ozvezdje":"Scutum", "ozvezdje":"Ščit"},
	{"iau":"Vul", "l_ozvezdje":"Vulpecula", "ozvezdje":"Lisička"},
	{"iau":"Sgr", "l_ozvezdje":"Sagittarius", "ozvezdje":"Strelec"},
	{"iau":"Cyg", "l_ozvezdje":"Cygnus", "ozvezdje":"Labod"},
	{"iau":"Cap", "l_ozvezdje":"Capricornus", "ozvezdje":"Kozorog"},
	{"iau":"And", "l_ozvezdje":"Andromeda", "ozvezdje":"Andromeda"},
	{"iau":"And", "l_ozvezdje":"Andromeda", "ozvezdje":"Andromeda"},
	{"iau":"Tri", "l_ozvezdje":"Triangulum", "ozvezdje":"Trikotnik"},
	{"iau":"Per", "l_ozvezdje":"Perseus", "ozvezdje":"Perzej"},
	{"iau":"Gem", "l_ozvezdje":"Gemini", "ozvezdje":"Dvojčka"},
	{"iau":"Aur", "l_ozvezdje":"Auriga", "ozvezdje":"Voznik"},
	{"iau":"Aur", "l_ozvezdje":"Auriga", "ozvezdje":"Voznik"},
	{"iau":"Aur", "l_ozvezdje":"Auriga", "ozvezdje":"Voznik"},
	{"iau":"Cyg", "l_ozvezdje":"Cygnus", "ozvezdje":"Labod"},
	{"iau":"UMa", "l_ozvezdje":"Ursa Major", "ozvezdje":"Veliki medved"},
	{"iau":"CMa", "l_ozvezdje":"Canis Major", "ozvezdje":"Veliki pes"},
	{"iau":"Ori", "l_ozvezdje":"Orion", "ozvezdje":"Orion"},
	{"iau":"Ori", "l_ozvezdje":"Orion", "ozvezdje":"Orion"},
	{"iau":"Cnc", "l_ozvezdje":"Cancer", "ozvezdje":"Rak"},
	{"iau":"Tau", "l_ozvezdje":"Taurus", "ozvezdje":"Bik"},
	{"iau":"Pup", "l_ozvezdje":"Puppis", "ozvezdje":"Krma"},
	{"iau":"Pup", "l_ozvezdje":"Puppis", "ozvezdje":"Krma"},
	{"iau":"Hya", "l_ozvezdje":"Hydra", "ozvezdje":"Vodna kača"},
	{"iau":"Vir", "l_ozvezdje":"Virgo", "ozvezdje":"Devica"},
	{"iau":"Mon", "l_ozvezdje":"Monoceros", "ozvezdje":"Samorog"},
	{"iau":"CVn", "l_ozvezdje":"Canes Venatici", "ozvezdje":"Lovska psa"},
	{"iau":"Cas", "l_ozvezdje":"Cassiopeia", "ozvezdje":"Kasiopeja"},
	{"iau":"Com", "l_ozvezdje":"Coma Berenices", "ozvezdje":"Berenikini kodri"},
	{"iau":"Sgr", "l_ozvezdje":"Sagittarius", "ozvezdje":"Strelec"},
	{"iau":"Sgr", "l_ozvezdje":"Sagittarius", "ozvezdje":"Strelec"},
	{"iau":"Lyr", "l_ozvezdje":"Lyra", "ozvezdje":"Lira"},
	{"iau":"Lyr", "l_ozvezdje":"Lyra", "ozvezdje":"Lira"},
	{"iau":"Vir", "l_ozvezdje":"Virgo", "ozvezdje":"Devica"},
	{"iau":"Vir", "l_ozvezdje":"Virgo", "ozvezdje":"Devica"},
	{"iau":"Vir", "l_ozvezdje":"Virgo", "ozvezdje":"Devica"},
	{"iau":"Vir", "l_ozvezdje":"Virgo", "ozvezdje":"Devica"},
	{"iau":"Oph", "l_ozvezdje":"Ophiuchus", "ozvezdje":"Kačenosec"},
	{"iau":"CVn", "l_ozvezdje":"Canes Venatici", "ozvezdje":"Lovska psa"},
	{"iau":"Com", "l_ozvezdje":"Coma Berenices", "ozvezdje":"Berenikini kodri"},
	{"iau":"Leo", "l_ozvezdje":"Leo", "ozvezdje":"Lev"},
	{"iau":"Leo", "l_ozvezdje":"Leo", "ozvezdje":"Lev"},
	{"iau":"Cnc", "l_ozvezdje":"Cancer", "ozvezdje":"Rak"},
	{"iau":"Hya", "l_ozvezdje":"Hydra", "ozvezdje":"Vodna kača"},
	{"iau":"Sgr", "l_ozvezdje":"Sagittarius", "ozvezdje":"Strelec"},
	{"iau":"Sgr", "l_ozvezdje":"Sagittarius", "ozvezdje":"Strelec"},
	{"iau":"Sge", "l_ozvezdje":"Sagitta", "ozvezdje":"Puščica"},
	{"iau":"Aqr", "l_ozvezdje":"Aquarius", "ozvezdje":"Vodnar"},
	{"iau":"Aqr", "l_ozvezdje":"Aquarius", "ozvezdje":"Vodnar"},
	{"iau":"Psc", "l_ozvezdje":"Pisces", "ozvezdje":"Ribi"},
	{"iau":"Sgr", "l_ozvezdje":"Sagittarius", "ozvezdje":"Strelec"},
	{"iau":"Per", "l_ozvezdje":"Perseus", "ozvezdje":"Perzej"},
	{"iau":"Cet", "l_ozvezdje":"Cetus", "ozvezdje":"Kit"},
	{"iau":"Ori", "l_ozvezdje":"Orion", "ozvezdje":"Orion"},
	{"iau":"Lep", "l_ozvezdje":"Lepus", "ozvezdje":"Zajec"},
	{"iau":"Sco", "l_ozvezdje":"Scorpius", "ozvezdje":"Škorpijon"},
	{"iau":"UMa", "l_ozvezdje":"Ursa Major", "ozvezdje":"Veliki medved"},
	{"iau":"UMa", "l_ozvezdje":"Ursa Major", "ozvezdje":"Veliki medved"},
	{"iau":"Hya", "l_ozvezdje":"Hydra", "ozvezdje":"Vodna kača"},
	{"iau":"Vir", "l_ozvezdje":"Virgo", "ozvezdje":"Devica"},
	{"iau":"Com", "l_ozvezdje":"Coma Berenices", "ozvezdje":"Berenikini kodri"},
	{"iau":"Vir", "l_ozvezdje":"Virgo", "ozvezdje":"Devica"},
	{"iau":"Vir", "l_ozvezdje":"Virgo", "ozvezdje":"Devica"},
	{"iau":"Com", "l_ozvezdje":"Coma Berenices", "ozvezdje":"Berenikini kodri"},
	{"iau":"Vir", "l_ozvezdje":"Virgo", "ozvezdje":"Devica"},
	{"iau":"Vir", "l_ozvezdje":"Virgo", "ozvezdje":"Devica"},
	{"iau":"Com", "l_ozvezdje":"Coma Berenices", "ozvezdje":"Berenikini kodri"},
	{"iau":"Her", "l_ozvezdje":"Hercules", "ozvezdje":"Krma"},
	{"iau":"Pup", "l_ozvezdje":"Puppis", "ozvezdje":"Krma"},
	{"iau":"CVn", "l_ozvezdje":"Canes Venatici", "ozvezdje":"Lovska psa"},
	{"iau":"Leo", "l_ozvezdje":"Leo", "ozvezdje":"Lev"},
	{"iau":"Leo", "l_ozvezdje":"Leo", "ozvezdje":"Lev"},
	{"iau":"UMa", "l_ozvezdje":"Ursa Major", "ozvezdje":"Veliki medved"},
	{"iau":"Com", "l_ozvezdje":"Coma Berenices", "ozvezdje":"Berenikini kodri"},
	{"iau":"Com", "l_ozvezdje":"Coma Berenices", "ozvezdje":"Berenikini kodri"},
	{"iau":"Com", "l_ozvezdje":"Coma Berenices", "ozvezdje":"Berenikini kodri"},
	{"iau":"UMa", "l_ozvezdje":"Ursa Major", "ozvezdje":"Veliki medved"},
	{"iau":"Dra", "l_ozvezdje":"Draco", "ozvezdje":"Zmaj"},
	{"iau":"Cas", "l_ozvezdje":"Cassiopeia", "ozvezdje":"Kasiopeja"},
	{"iau":"Vir", "l_ozvezdje":"Virgo", "ozvezdje":"Devica"},
	{"iau":"Leo", "l_ozvezdje":"Leo", "ozvezdje":"Lev"},
	{"iau":"CVn", "l_ozvezdje":"Canes Venatici", "ozvezdje":"Lovska psa"},
	{"iau":"Oph", "l_ozvezdje":"Ophiuchus", "ozvezdje":"Kačenosec"},
	{"iau":"UMa", "l_ozvezdje":"Ursa Major", "ozvezdje":"Veliki medved"},
	{"iau":"UMa", "l_ozvezdje":"Ursa Major", "ozvezdje":"Veliki medved"},
	{"iau":"And", "l_ozvezdje":"Andromeda", "ozvezdje":"Andromeda"}];
var tabela = document.getElementById("tabela");

var i = 0;
for (const el of data) {
	var vrsta = tabela.insertRow(i+1);
	var ime = vrsta.insertCell(0);
	var iau = vrsta.insertCell(1);
	var l_ozvezdje = vrsta.insertCell(2);
	var ozvezdje = vrsta.insertCell(3);
	ime.innerHTML = "M" + (i+1);
	ime.className = "ime";
	iau.innerHTML = data[i].iau;
	iau.className = "iau";
	l_ozvezdje.innerHTML = data[i].l_ozvezdje;
	l_ozvezdje.className="l_ozvezdje";
	ozvezdje.innerHTML = data[i].ozvezdje;
	ozvezdje.className="ozvezdje";
	i++;
}